FROM maven:4.0 as BUILDER

WORKDIR /usr/src/app

COPY ./pom.xml ./pom.xml
COPY ./src ./src

RUN --mount=type=cache,target=/root/.m2 mvn package -DskipTests

FROM eclipse-temurin:17-alpine

WORKDIR /usr/src/app

ENV SERVER_PORT=80
ENV DB_SHOW_SQL=false
ENV DOCKERIZE_VERSION v0.6.1

COPY --from=BUILDER C://instituteManagement/src*.jar ./api.jar

RUN apk add --no-cache openssl

EXPOSE ${SERVER_PORT}

ENTRYPOINT [ "java", "-jar", "api.jar" ]